### ISSUE TITLE
feat: consume common interface for Sender/Receiver 

### ISSUE THREAD

**Issue by weboko** [waku-org/js-noise#14]
After publishing Noise example it is visible that whoever uses library will need to declare herself Sender/Receiver pairs.
We should find a way to reduce this boilerplate code.

https://github.com/waku-org/js-waku-examples/pull/177#discussion_r1082108188

cc: @fryorcraken

**Comment by weboko** [comment]
Related to https://github.com/waku-org/js-waku/issues/1220
Should be resolved by https://github.com/waku-org/js-noise/pull/33

**Comment by fryorcraken** [comment]
The interface for "responder" does not use `IReceiver`. Is that expected?

**Comment by weboko** [comment]
Not at all. As I mentioned https://github.com/waku-org/js-waku-examples/pull/223#discussion_r1156529324 I will publish following PR for example and the lib. 
Let's indeed keep the issue open
